samliew/SO-mod-userscripts

- ShowDeletedMessagesInChat.user.js
When a user doesn't have access to view deleted message history, the message collapses incorrectly. For example:
This commit will only apply `.cmmt-deleted` if the history request succeeds. If it doesn't, the message is left unchanged.
> Fix styling issue when user doesn't have access to view history of deleted messages

- StackExchangeDarkMode.user.js
Without this exception, elements that contains the answer icons for accepted questions did get a fully green background like this: https://i.stack.imgur.com/PMV40.png
> Answer icons don't get green background

- StackExchangeDarkMode.user.js
Without this, mod OPs writing comments look a little broken: https://i.stack.imgur.com/65oun.png
With this change, there is the tiniest bump on top of the span (https://i.stack.imgur.com/JXJOd.png) but it looks more consistent than before.
> Defined background-color for mod-flair

- DiscussedOnMeta.user.js
- PostBanDeletedPosts.user.js
jQuery parses HTML with nested elements (such as a whole page) into a DOM by creating a new div and then setting the .innerHTML attribute. Unfortunately, this has side effects; Firefox will pick up the <link rel="shortcut icon" href="..."> node in the parsed document and change the favicon shown in the tab. This leads to confusing icons for most pages.
This patch changes this to using the DOMParser.parseFromString() API to parse the HTML into a new owner document before passing the result to jQuery; this separate owner document is not connected to the tab and so won't change the favicon shown.
>  Use DOMParser to produce separate document

- CommentFlagsHelper.user.js
I found the UX of rude / chatty comments to be very poor, especially at night when f.lux starts shifting towards more red, less blue light.
This update improves this for me, and uses better mark-up. Before:
> ![](https://user-images.githubusercontent.com/46775/76085216-83965280-5fa9-11ea-922b-37ecbd0b0b7b.png)
After:
> ![](https://user-images.githubusercontent.com/46775/76085362-c9ebb180-5fa9-11ea-9af8-bbade839db4d.png)
While the yellow background tends to fade and become less noticeable when the red-shifting kicks in, the bold still stands out, as does the underline on the rude comments. The red text, on the other hand, becomes almost painful to the eye.
> Better rude / chatty comment markup

- ChatImprovements.user.js
When loading longer messages, account for pre-formatted text, and replace the `<pre class="partial">` element with a `<pre class="full">` element with the message only processed to remove the 4-space indent.
> Don't mangle pre-formatted text when loading more

- DeletedUsersHelper.user.js
Minor stylistic improvement: this uses the same font-family list as Stack Overflow's existing `<pre>` element styles. Not only is this more consistent, but it looks a lot better on my machine, where "monospace" translates to "Courier New". If "Consolas" is available, it looks much better and is much more readable, especially with bold text.
> Use same monospace font families as Stack Overflow does for <pre>.

- AdditionalInlinePostModMenu.user.js
The background color was previously forced to white, which looked fine
on normal posts (which have a white background), but was not correct
on deleted posts (which have a reddish-gray background). I presume
that it would also not be correct when the dark theme is used (although
I haven't tested it). I see no point in explicitly specifying a background
color here; it should just inherit its parent's background color.
> Remove background color from inline mod menu.

- ModFlaggerStats.user.js
Added the Stacks button styles to the "Load flagger stats" button
in order to make it align and blend in better.
I chose a filled standard button style, not a primary button, to make
the button visible, without being annoying. This is not a primary
button or one that performs an important action.
> Tweak appearance of "Load flagger stats" button.

- PostBanDeletedPosts.user.js
This ensures it is laid out correctly with the rest of the page.
Without this change, the div messes up the layout in Firefox:
With the change, the information is properly placed between post and comments:
> Mark post-banned info div as a post cell

- AdditionalInlinePostModMenu.user.js
This almost certainly needs more work, but this is the minimal change that I determined needs to be made to make the menu additions appear again.
These changes by SE staff were not announcement or documented anywhere, but they made significant (and apparently superfluous) changes to the DOM. One discussion is here: https://meta.stackexchange.com/questions/359477/capitalization-of-post-action-links-is-causing-multiple-rows-of-links
> Minimal tweak to AdditionalInlinePostModMenu for compliance with SE changes to post menus

- PostHeadersQuestionToc.user.js
The named anchors functionality is wrapping all headings (`h1`, `h2`, `h3`) in posts inside `a` tags. By doing so, the style defined in [`stacks.css`](https://cdn.sstatic.net/Shared/stacks.css) thinks they are the last children of the post body and therefore sets `margin-bottom: 0;`:
```css
[...] .s-prose h1:last-child, .s-prose h2:last-child, .s-prose h3:last-child, [...] {
margin-bottom: 0;
}
```
This creates an awkward situation in which headings are way too close to the first following paragraph.
Original:
With the userscript applied:
This commit solves the issue by simply adding a CSS rule to `revert` the style for headings inside `a.js-named-anchor`.
Not sure if I should change the version of the userscript, let me know.
> Table of contents userscript: fix broken post headings bottom margin

- ModMessageHelper.user.js
Adds an underline to the label for "suspension reason" to make it clearer to anyone using this userscript that this field is able to change the message displayed on the suspended user's public profile.
> Add clarification highlight / title

- DeletedUsersHelper.user.js
The format of the text provided by SE appears to have changed enough such that the line on which the script was assuming the IP address would exist is no longer the correct line. Rather than hard code a specific line, this changes the selection of which line to use to be the last line in the details which includes the text "IP:".
> Deleted Users Helper: For the user's last IP address, get it from the last line with "IP:"

- ModFlaggerStats.user.js
Updated the selector to append the little badge next to the user name in the profile pages. It was broken when profiles were updated to [the new responsive design](https://meta.stackexchange.com/questions/370964/now-live-a-fully-responsive-profile).
> ModFlaggerStats: fix broken selector on new profiles

- .gitignore
- SOMU-options.user.js
- UserReviewBanHelper.user.js
- globals.d.ts
- jsconfig.json
- package-lock.json
- package.json
This PR adds support for sending review ban stats to the summary spreadsheet via the userscript.
For the update to work, the production version has to create a Google Cloud Project and set 3 variables (required by Google):
```typescript
const sheetsApiKey = ""; // API key created on https://console.cloud.google.com/apis/credentials
const appClientId = ""; // OAuth 2.0 Client IDs created on https://console.cloud.google.com/apis/credentials
const statsSpreadId = ""; // spreadsheet id, i.e. 1GIH-6CH58lJbQ18vPcsrBVzlHwjOmuYTxktMbLV9TWk
```
A potential caveat is that the `https://www.googleapis.com/auth/spreadsheets` (read/write) scope requested from the user can be quite scary for security-conscious users, but there is no other way around for allowing writes to a spreadsheet on behalf of a …
> WIP: Add ability to send review ban stats to the summary spreadsheet

- QuestionListsHelper.user.js
In dark mode on hover the background of comments was white and the comment text was very light grey, thus there was almost no contrast.
Changed the background colour to use the defined variable from the theme.
> Fixed background colour in dark mode

- ModMessageHelper.user.js
Following latest SE change to top bar the padding here is applied to the user card that appears in the top bar as well as the other user cards that appear on the page, pushing the users reputation, badges etc. of the top of the screen. Change disables padding-bottom css for the user card in the top bar.
> Resolve issue with floating user card in top bar

- DeletedUsersHelper.user.js
The `userDetails` text is added to the text box with 4 newline characters, because when creating the variable the text starts with two newlines, and then another 2 are added two lines down. Remove the first 2 of these.
> DeletedUsersHelper: Remove spurious newlines

- ModMessageHelper.user.js
Instead of banning double quotes, escape double quotes by replacing them with `&#34` HTML entities.
> ModMessageHelper: Remove the 'no double quotes' limitation

- SOMU-options.user.js
- globals.d.ts
This PR fixes the `SOMU` global initialization as `var SOMU = ...` is not able to escape the sandboxed `window`.
It also explicitly grants access to `unsafeWindow` via a `@grant` header (previously implied).
As a minor addition to the PR come improvements to shared typings and a bit of formatting.
> SOMU-options SOMU global fix

- NotAnAnswerFlagQueueHelper.user.js
This reverts 473be9f38bb54a2b732e6e32476a29463afb199d; this change is *amazingly* annoying:
- the re-sort happens at an unspecified time after loading a flag page. It regularly causes a post I was already interacting with to move, and then I have to search for it again.
- I can't pick any other another sort option, as that *triggers a page load*, so flagger ranking is loaded again, and the page is resorted.
Please leave this a manual choice.
Can I suggest that if you feel strongly about this sort option being the default for you, that we make this a preference? Perhaps store the last selected sort option and use that on page load.
> Do not auto-sort by rank

- ModMessageHelper.user.js
Not sure what version scheme you prefer, so just bumped the minor instead of the major.
Bit of a draft though. It's not really a general template, but specifically tailored for the support number spammers. If a general one makes more sense than this one, I'll edit it.
> Add template for closing spam, instead of flagging

- ReduceClutter.user.js
Remove zero-or-more (`*`) quantifier from closing `[\s-_]` group; with the
quantifier any element past the first that *starts* with one of the words (such
as *islam* or *haspero* or *lovelace*) would be removed as there are zero
spaces, dashes or underscores past the letters matched before this group.
Remove the `is.at` alternative, it matches too broadly; there are loads of valid
second names with *is* LETTER *mat*. Names with *is at* are already matched by
the *is* alternative..
> Avoid false positives in short usernames regex

- ReviewQueueHelper.user.js
RQH is not designed to work on the main `/review` page, however, the permissive `/review*` match allows it to run there, causing it to error out when fetching flags quota in `getFlagsQuota`. This PR restricts `@include` headers to review-specific pages.
> Do not load RQH on /review page

- ReviewQueueHelper.user.js
This PR fixes a minor bug with unconditionally adding `/timeline` link and icon to post action sidebar in review queues (happens because SE finally added the link) leading to duplicated timeline icons:
> Only add timeline link if missing (RQH)

- PostBanDeletedPosts.user.js
SO updated the search selectors again. Highlights:
* `.question-hyperlink` no longer exists
* `.answer-hyperlink` is now a thing
* `.s-link` with a data selector gets questions; just `.s-link` may be enough
* `.search-result` is no longer a thing either; replaced with `.s-card`. Didn't touch the first selector because I have no idea what context it's used in.
* And to add insult to injury, two selectors are now required for the filter, because while `.s-link` is applied to question links, answers have `.answer-hyperlink`, and there's no overlap beyond the data attribute, but relying on it entirely doesn't feel like a great idea
A test on both question and answer bans indicates this should work, but feel free …
> Fix search selectors

- ReviewQueueHelper.user.js
Unconditionally appending our own version of "follow" causes the button to appear twice (and in an incorrect state) since SE fixed that too. This PR makes RHQ look up the follow button and only append the custom one if not present.
> only insert 'follow' button if the native button is missing

- ReviewQueueHelper.user.js
This PR revives the daily flag and close vote quota stats broken by SE's rework of the queues:
This includes:
- a rework of how remaining daily quota is fetched to make it less brittle (as it broke on MSO, unfortunately)
- exclusion of /stats pages as those cause the quota fetch to err out
- a rewiring of the quota stats elements to the new review UI
- a fix for audit toasts (turns out, the `duration` parameter was in seconds, not ms)
- some minor linting (semicolons, spaces, and all that jazz)
Styling adjustments to be included in later updates.
> Dawn of the living stats & toasts

- ReviewQueueHelper.user.js
This update ensures that the quota retrieval is even more robust (first question can be closed by the time we fetch the stats), makes insertion of the "share" button conditional (to avoid duplicate "share" buttons), and makes a minor styling adjustment to make review keywords visible again and play well with dark mode.
Light mode keywords:
Dark mode keywords:
> 28 keywords later

- ChatImprovements.user.js
Currently, the topbar is not modified at all unless the script is running in the context where the topbar is not available natively (i.e. in a room). This results in a very useful feature of one-click switching between chat hostnames to be unavailable. This PR addresses that by ensuring the switcher is added to the topbar regardless of context:
No
> Once upon a topbar in Chat

- ChatImprovements.user.js
This PR is an extension of #140 and enables chat topbar on `/transcript` pages (they lack `#chat-body` element) + ensures that information not accessible on those pages is not used (i.e., the current user info):
No
> No Transcript For Old Topbars

- UserReviewBanHelper.user.js
- Adds a nice little table with a breakdown of mods
These have not been hooked up into the spreadsheet, because I don't see much use for it aside checking how many mods are looking at reviews at any given time. I imagine these are better used internally anyway
> Add moderator stats

- ModMessageHelper.user.js
The "demands to show effort/'not a code-writing service'" template was
written by me.
"promotional content; answers not self-contained" was written by Makyen,
and is used with permission.
"generic year-long ban" is the same message used by
AdditionalInlinePostModMenu that is designed to fit within the notification
seen by a recreated account.
> Add "demands to show effort/'not a code-writing service'", "promotional content; answers not self-contained", and "generic year-long ban" templates

- ModMessageHelper.user.js
Reduce display impact when not adding menu
This PR:
1. Removes the js-mod-message-menu class when there isn't a .js-mod-message-link descendant.
2. Not display the .js-mod-message-menu .user-action-time when the .user-action-time is blank
3. Requires the .js-mod-message-menu class to be present to apply some CSS to descendants.
Closes #150
> Reduce Mod Message Helper display impact when not adding menu

- ModMessageHelper.user.js
SE has changed to separately adding the signature to the resulting text, rather than have the signature embedded in the text for each mod message option. Thus, if we include the signature in the text for the template options which are being added, there end up being two copies of the signature.
This just changes the logic so we only add the (extra) signature when the template has `addSignature: true`. Given that no template has that defined, we don't add an additional signature.
We should probably look at being able to remove the signature which SE adds when `addSignature: false` is in the template,
but that's not implemented at this time, as this is just a minimal quick change to prevent having two …
> MMH: prevent double signature

- DeletedUsersHelper.user.js
Deleted users page was added today... without a link to the user
`https://stackoverflow.com/admin/post-comments-by-deleted-user/<userid>`
This PR adds that link to the header
> Added support for new deleted users comment page

- ModMessageHelper.user.js
- Prevent the somu-mod-message-menu menu from being off-screen upon opening, which could happen at some screen widths.
No.
> MMH: Prevent somu-mod-message-menu from opening off-screen (left/right)

- ChatImprovements.user.js
The PR introduces several minor improvements to the Chat Improvements userscript, specifically:
1. Fixes top bar search input positioning (top margin);
2. Shows more "my room" links at the same time (2 in a row) if the width of the viewport allows for it (by using Flexbox);
3. Adds a factory function for top bar navigation buttons (to be expanded upon in further PRs);
Two rooms per row shown in the "my rooms" sidebar widget:
Top navigation bar search input top margin adjusted:
> Thrice upon a navbar

- ModMessageHelper.user.js
- Reduce the length of the ChatGPT `templateName` to <= 55 characters, so it won't prevent the message from being in the moderator inbox regardless 
No, but there was discussion/investigation in chat, starting at https://chat.stackoverflow.com/transcript/message/55825687#55825687
> Mod Message Helper: reduce ChatGPT template name length

- ModMessageHelper.user.js
- Tell the user if the length of the template name + user's username will prevent the message from appearing in the moderator inbox
- Add a text indication when the length of the template name will prevent the mod message from being in the mod inbox.
- Add a tooltip to the above indicator and the `<input>` with a more detailed explanation and current state (i.e. current character count and max limit for showing in the mod inbox).
- Add a tooltip to the template name label which explains where the template name is used.
No
> Mod Message Helper:  tell user when template name length will prevent mod message from being in the mod inbox
